### ISSUE TITLE
Add support for P2js

### ISSUE THREAD

**Issue by nasawz** [danzen/zimjs#25]

**Comment by danzen** [comment]
Great idea - we were certainly wanting to look at that.  We'll bring the request in to our Slack Team and see what comes of it.  It would most likely be a helper class like the ZIM physics.js works with Box2D.

**Comment by danzen** [comment]
Getting there - a physics overhaul is due over the holidays this year.

**Comment by nasawz** [comment]
It was magic ！

**Comment by danzen** [comment]
@nasawz we have been looking through the current state of physics engines with an eye on mobile... do you have an recommendations at this point - or does P2 still seem right for you?  I am not sure from what I have read that P2 will give us a magnitude of better performance on mobile than Box2D.  Phaser has moved to Matter instead of P2... We are abstracting the engine completely in the upcoming version of ZIM - so the interface to the engine is not an issue.  I think we need an engine like Arcade Physics in Phaser - something simple and fast based on rectangles or polygons and circles - so that is what we are looking for.  Any suggestions along that line? We could use two engines on basic and one like P2/Box2D/Matter.   It is that basic one that we are not sure of.
Our last physics example is here: https://zimjs.com/droid/
Oh... added a panning version of a world here: https://zimjs.com/explore/follow.html
And a CodePen: https://codepen.io/danzen/details/bKvybq

**Comment by danzen** [comment]
We have integrated physics in ZIM TEN.  Box2D and the physics.js helper module is still needed but all the commands are in ZIM and in the docs.  Physics is much easier now - see https://zimjs.com/physics/
